<?php

return [
    [
        'name' => 'typeBoleta',
        'valueText' => 'Semanal',
        'valueNumber' => 1,
        'module' => 'boleta',
        'description' => 'Tipo de Boleta Semanal',
    ],
    [
        'name' => 'typeBoleta',
        'valueText' => 'Mensual',
        'valueNumber' => 2,
        'module' => 'boleta',
        'description' => 'Tipo de Boleta Semanal',
    ],
    [
        'name' => 'daysOfWeek',
        'valueText' => null,
        'valueNumber' => 7,
        'module' => null,
        'description' => 'Dias de una semana',
    ],
    [
        'name' => 'empresa',
        'valueText' => 'SERMEIND FABRICACIONES INDUSTRIALES S.A.C.',
        'valueNumber' => 0,
        'module' => 'boleta',
        'description' => 'Nombre la empresa sermeind',
    ],
    [
        'name' => 'ruc',
        'valueText' => '20540001384',
        'valueNumber' => 0,
        'module' => 'boleta',
        'description' => 'Ruc la empresa sermeind',
    ],
    [
        'name' => 'horasXDia',
        'valueText' => null,
        'valueNumber' => 8,
        'module' => 'boleta',
        'description' => 'Horas trabajadas por día',
    ],
    [
        'name' => 'diasMes',
        'valueText' => null,
        'valueNumber' => 30,
        'module' => 'boleta',
        'description' => 'Dias por mes',
    ],
    [
        'name' => 'horasSemanales',
        'valueText' => null,
        'valueNumber' => 48,
        'module' => 'boleta',
        'description' => 'Horas máximas por semana',
    ],
    [
        'name' => 'tipoDomumento',
        'valueText' => 'DNI',
        'valueNumber' => 1,
        'module' => 'boleta',
        'description' => 'Tipo de documento DNI',
    ],
    [
        'name' => 'tipoDomumento',
        'valueText' => 'RUC',
        'valueNumber' => 2,
        'module' => 'boleta',
        'description' => 'Tipo de documento RUC',
    ],
    [
        'name' => 'tipoDomumento',
        'valueText' => 'C.E.',
        'valueNumber' => 3,
        'module' => 'boleta',
        'description' => 'Tipo de documento C.E.',
    ],
    [
        'name' => 'address',
        'valueText' => 'AV. EL POLO 670, SANTIAGO DE SURCO, LIMA',
        'valueNumber' => null,
        'module' => null,
        'description' => 'Direccion de la tienda',
    ],
    [
        'name' => 'typeFactura',
        'valueText' => null,
        'valueNumber' => null,
        'module' => null,
        'description' => null,
    ],
];
