<?php

return [
    'dashboard'=>'DASHBOARD',
    'materialType'=>'TIPO DE MATERIAL',
    'user'=>'USUARIOS',
    'role'=>'ROLES',
    'supplier'=>'PROVEEDORES',
    'permission'=>'PERMISOS',
    'customer'=>'CLIENTES',
    'category'=>'CATEGORÍAS',
    'material'=>'MATERIALES',
    'quote'=>'COTIZACIONES',
    'area'=>'ÁREAS',
    'warehouse'=>'ALMACENES',
    'shelf'=>'ANAQUELES',
    'level'=>'NIVELES',
    'container'=>'CONTENEDORES',
    'location'=>'UBICACIONES',
    'report'=>'REPORTES',
    'email'=>'EMAILS',
    'exampler'=>'MODELOS',
    'brand' => 'MARCAS',
    'subcategory' => 'SUBCATEGORÍAS',
    'subType' => 'SUB TIPOS',
    'warrant' => 'CÉDULA',
    'quality' => 'CALIDAD',
    'position' => 'POSICIONES',
    'unitMeasure' => 'UNIDAD DE MEDIDA',
    'contactName' => 'NOMBRE DE CONTACTO',
    'transfer' => 'TRANSFERENCIAS',
    'entryPurchase' => 'ENTRADA POR COMPRA',
    'entryScrap' => 'RETACERÍA',
    'entryInventory' => 'INVENTARIO',
    'output' => 'SALIDAS',
    'request' => 'SOLICITUDES',
    'typeScrap' => 'TIPO RETACERÍA',
    'invoice' => 'FACTURAS',
    'orderPurchaseExpress' => 'ORDENES COMPRA EXPRESS',
    'orderPurchaseNormal' => 'ORDENES COMPRA COMUN',
    'orderExecution' => 'ORDENES EJECUCIÓN',
    'orderService' => 'ORDENES DE SERVICIO',
    'service' => 'SERVICIOS',
    'paymentDeadline' => 'PLAZOS DE PAGO',
    'credit' => 'CRÉDITOS',
    'orderExecutionAlmacen' => 'ORDENES EJECUCION PARA ALMACEN',
    'followMaterials' => 'SEGUIMIENTO DE MATERIALES',
    'requestPurchaseOperator' => 'SOLICITUD DE COMPRA',
    'categoryInvoice'=>'CATEGORÍAS FACTURAS',
    'worker' => 'COLABORADORES',
    'porcentageQuote' => 'PORCENTEAJES DE COTIZACION',
    'timeline' => 'CRONOGRAMAS',
    'assistance' => 'ASISTENCIAS',
    'navbar' => 'BARRA NAVEGACION',
    'percentageWorker' => 'PORCENTAJES DE RRHH',
    'areaWorker' => 'ÁREAS DE LA EMPRESA',
    'requestSimple' => 'SOLICITUDES AREAS',
    'hourSpecial' => 'MOD. HORAS ESPECIALES',
    'medicalRest' => 'DESCANSOS MEDICOS',
    'vacation' => 'VACACIONES',
    'license' => 'LICENCIAS',
    'unpaidLicense' => 'LICENCIAS SIN GOZO',
    'permit' => 'PERMISOS TRABAJADORES',
    'permitHour' => 'PERMISOS POR HORAS TRABAJADORES',
    'suspension' => 'SUSPENSIONES',
    'discountContribution' => 'DESCUENTOS Y APORTES',
    'discount' => 'DESCUENTOS',
    'loan' => 'PRÉSTAMOS',
    'gratification' => 'GRATIFICACIÓN',
    'refund' => 'REEMBOLSOS',
    'fifthCategory' => 'RENTA QUINTA CATEGORIA',
    'alimony' => 'PENSIÓN ALIMENTOS',
    'paySlip' => 'BOLETAS DE PAGO',
    'orderPurchaseFinance' => 'ORDENES DE COMPRA FINANZAS',
    'bill' => 'TIPOS DE PAGO',
    'expense' => 'RENDICIÓN DE CUENTAS',
    'bonusRisk' => 'BONOS ESPECIALES',
    'personalPayments' => 'PAGO AL PERSONAL',
    'projection' => 'PROYECCION DE SUELDOS',
    'financeWorks' => 'TRABAJOS EN FINANZAS',
    'workerAccount' => 'CUENTAS BANCARIAS TRABAJADORES',
    'supplierAccount' => 'CUENTAS BANCARIAS PROVEEDORES',
    'defaultEquipment' => 'CATALOGO EQUIPOS',
    'sales' => 'VENTAS',
    'proforma' => 'PRE COTIZACIONES',
    'expenseSupplier' => 'EGRESOS PROVEEDORES',
    'inventory' => 'INVENTARIO FISICO',
    'files' => 'IMPORTAR ARCHIVOS',
    'referralGuide' => 'GUIA DE REMISION',
    'materialSetting' => 'CONFIGURACION DE MATERIALES',
    'dataGeneral' => 'DATOS GENERAALES',
    'quoteSale' => 'COTIZACIONES DE VENTA',
    'promotionLimit' => 'PROMOCIONES CON LIMITE',
    'puntoVenta' => 'PUNTO DE VENTA',
    'caja' => 'CAJA',
    'gananciaDiaria' => 'GANANCIA DIARIA',
    'metas' => 'METAS',
    'promotions' => 'PROMOCIONES',

    'cashBox' => 'CASH BOXES',
    'cashBoxSubtype' => 'CASH BOXES SUBTIPOS',
    'configUserWeb' => 'CONFIGURAR USUARIOS WEB',

    'genero' => 'GÉNEROS',
    'color' => 'COLORES',
    'talla' => 'TALLAS',

    'companyStockItem' => 'CATÁLOGO POR EMPRESA',

    'company' => 'EMPRESAS',

    'branch' => 'SUCURSALES',

    'companyBankAccount' => 'CUENTAS BANCARIAS DE LA EMPRESA',
    'companySetting' => 'CONFIGURACIONES DE LA EMPRESA',

    'priceListMaterial' => 'LISTAS DE PRECIOS',
];