<?php

return [

    [
        'key' => 'sales.allow_partial_payments',
        'label' => 'Permitir pagos parciales',
        'module' => 'sales',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'description' => 'Permite registrar ventas utilizando pagos parciales.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'finance.base_currency',
        'label' => 'Moneda base',
        'module' => 'finance',
        'scope' => 'company',
        'value_type' => 'enum',
        'default_value' => 'PEN',
        'options' => ['PEN', 'USD',],
        'description' => 'Moneda base utilizada por la empresa para sus operaciones y cálculos internos.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'pos.require_worker',
        'label' => 'Requerir trabajador en punto de venta',
        'module' => 'pos',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si el punto de venta exige seleccionar un trabajador antes de registrar la venta.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'sales.goals.frequency',
        'label' => 'Frecuencia de metas de venta',
        'module' => 'sales',
        'scope' => 'company',
        'value_type' => 'enum',
        'default_value' => null,
        'options_json' => [
            'semanal',
            'quincenal',
            'mensual',
        ],
        'description' => 'Define la frecuencia utilizada para las metas comerciales de la empresa.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.minimum_stock.show_alerts',
        'label' => 'Mostrar alertas de stock mínimo',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se muestra el resumen de productos desabastecidos o próximos a alcanzar su stock mínimo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.stock_notifications.popup',
        'label' => 'Notificación emergente de stock',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se muestran notificaciones emergentes cuando un producto alcanza un nivel de stock bajo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.stock_notifications.bell',
        'label' => 'Notificación en campana de stock',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se generan notificaciones internas en la campana cuando un producto alcanza un nivel de stock bajo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.stock_notifications.email',
        'label' => 'Notificación por correo de stock',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se envían correos cuando un producto alcanza un nivel de stock bajo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.stock_notifications.telegram',
        'label' => 'Notificación por Telegram de stock',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se envían notificaciones por Telegram cuando un producto alcanza un nivel de stock bajo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'supplier_credit.expiration_warning_days',
        'label' => 'Días de alerta antes del vencimiento',
        'module' => 'supplier_credit',
        'scope' => 'company',
        'value_type' => 'integer',
        'default_value' => '7',
        'options_json' => null,
        'description' => 'Cantidad de días antes del vencimiento para considerar un crédito de proveedor como próximo a vencer.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.rotation.low_start',
        'label' => 'Inicio de rotación baja',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'decimal',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Porcentaje mínimo para clasificar un producto con rotación baja.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.rotation.low_end',
        'label' => 'Fin de rotación baja',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'decimal',
        'default_value' => '40',
        'options_json' => null,
        'description' => 'Porcentaje máximo para clasificar un producto con rotación baja.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.rotation.medium_start',
        'label' => 'Inicio de rotación media',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'decimal',
        'default_value' => '40',
        'options_json' => null,
        'description' => 'Porcentaje mínimo para clasificar un producto con rotación media.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.rotation.medium_end',
        'label' => 'Fin de rotación media',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'decimal',
        'default_value' => '70',
        'options_json' => null,
        'description' => 'Porcentaje máximo para clasificar un producto con rotación media.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.rotation.high_start',
        'label' => 'Inicio de rotación alta',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'decimal',
        'default_value' => '70',
        'options_json' => null,
        'description' => 'Porcentaje mínimo para clasificar un producto con rotación alta.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'hr.break_hours',
        'label' => 'Horas de refrigerio',
        'module' => 'hr',
        'scope' => 'company',
        'value_type' => 'decimal',
        'default_value' => '1',
        'options_json' => null,
        'description' => 'Cantidad de horas de refrigerio que se descuentan de la jornada laboral.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.profile.website',
        'label' => 'Sitio web',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Sitio web público de la empresa.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.branding.logo',
        'label' => 'Logotipo',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Ruta o URL del logotipo principal de la empresa.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.branding.logo_monochrome',
        'label' => 'Logotipo monocromático',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Ruta o URL de la versión monocromática del logotipo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.profile.whatsapp',
        'label' => 'WhatsApp',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Número de WhatsApp público de la empresa.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'catalog.show_prices',
        'label' => 'Mostrar precios en catálogo',
        'module' => 'catalog',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '1',
        'options_json' => null,
        'description' => 'Define si el catálogo web muestra los precios de los productos.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'catalog.show_presentations',
        'label' => 'Mostrar presentaciones',
        'module' => 'catalog',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '1',
        'options_json' => null,
        'description' => 'Define si se muestran las presentaciones o variantes en el catálogo web.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'catalog.footer_description',
        'label' => 'Descripción del pie de página',
        'module' => 'catalog',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Texto mostrado en el pie de página del catálogo web.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.social.facebook',
        'label' => 'Facebook',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Enlace público de Facebook.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.social.twitter',
        'label' => 'Twitter / X',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Enlace público de Twitter o X.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.social.youtube',
        'label' => 'YouTube',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Enlace público de YouTube.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.social.instagram',
        'label' => 'Instagram',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Enlace público de Instagram.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.social.pinterest',
        'label' => 'Pinterest',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Enlace público de Pinterest.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.social.tiktok',
        'label' => 'TikTok',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Enlace público de TikTok.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'company.branding.quote_text',
        'label' => 'Texto institucional',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Texto o frase institucional mostrada en documentos comerciales.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],
    [
        'key' => 'company.branding.quote_reference',
        'label' => 'Referencia del texto institucional',
        'module' => 'company',
        'scope' => 'company',
        'value_type' => 'string',
        'default_value' => null,
        'options_json' => null,
        'description' => 'Referencia o autor asociado al texto institucional mostrado en documentos comerciales.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'payroll.pay_slip_frequency',
        'label' => 'Frecuencia de boleta de pago',
        'module' => 'payroll',
        'scope' => 'company',
        'value_type' => 'enum',
        'default_value' => 'semanal',
        'options_json' => [
            'semanal',
            'mensual',
            'anual',
        ],
        'description' => 'Define la frecuencia utilizada para el cálculo de las boletas de pago.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'payroll.days_per_week',
        'label' => 'Días por semana',
        'module' => 'payroll',
        'scope' => 'company',
        'value_type' => 'integer',
        'default_value' => '7',
        'options_json' => null,
        'description' => 'Cantidad de días utilizada como base semanal para cálculos de planilla.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'payroll.days_per_month',
        'label' => 'Días base por mes',
        'module' => 'payroll',
        'scope' => 'company',
        'value_type' => 'integer',
        'default_value' => '30',
        'options_json' => null,
        'description' => 'Cantidad de días base utilizada para cálculos mensuales de planilla.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'payroll.hours_per_day',
        'label' => 'Horas por día',
        'module' => 'payroll',
        'scope' => 'company',
        'value_type' => 'decimal',
        'default_value' => '8',
        'options_json' => null,
        'description' => 'Cantidad de horas utilizada como jornada diaria base.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'payroll.hours_per_week',
        'label' => 'Horas por semana',
        'module' => 'payroll',
        'scope' => 'company',
        'value_type' => 'decimal',
        'default_value' => '48',
        'options_json' => null,
        'description' => 'Cantidad de horas utilizada como jornada semanal base.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

];