<?php

return [

    [
        'key' => 'sales.allow_partial_payments',
        'label' => 'Permitir pagos parciales',
        'module' => 'sales',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'description' => 'Permite registrar ventas utilizando pagos parciales.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'finance.base_currency',
        'label' => 'Moneda base',
        'module' => 'finance',
        'scope' => 'company',
        'value_type' => 'enum',
        'default_value' => 'PEN',
        'options' => ['PEN', 'USD',],
        'description' => 'Moneda base utilizada por la empresa para sus operaciones y cálculos internos.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'pos.require_worker',
        'label' => 'Requerir trabajador en punto de venta',
        'module' => 'pos',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si el punto de venta exige seleccionar un trabajador antes de registrar la venta.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'sales.goals.frequency',
        'label' => 'Frecuencia de metas de venta',
        'module' => 'sales',
        'scope' => 'company',
        'value_type' => 'enum',
        'default_value' => null,
        'options_json' => [
            'semanal',
            'quincenal',
            'mensual',
        ],
        'description' => 'Define la frecuencia utilizada para las metas comerciales de la empresa.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.minimum_stock.show_alerts',
        'label' => 'Mostrar alertas de stock mínimo',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se muestra el resumen de productos desabastecidos o próximos a alcanzar su stock mínimo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],

    [
        'key' => 'inventory.stock_notifications.popup',
        'label' => 'Notificación emergente de stock',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se muestran notificaciones emergentes cuando un producto alcanza un nivel de stock bajo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],
    [
        'key' => 'inventory.stock_notifications.bell',
        'label' => 'Notificación en campana de stock',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se generan notificaciones internas en la campana cuando un producto alcanza un nivel de stock bajo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],
    [
        'key' => 'inventory.stock_notifications.email',
        'label' => 'Notificación por correo de stock',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se envían correos cuando un producto alcanza un nivel de stock bajo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],
    [
        'key' => 'inventory.stock_notifications.telegram',
        'label' => 'Notificación por Telegram de stock',
        'module' => 'inventory',
        'scope' => 'company',
        'value_type' => 'boolean',
        'default_value' => '0',
        'options_json' => null,
        'description' => 'Define si se envían notificaciones por Telegram cuando un producto alcanza un nivel de stock bajo.',
        'editable_by_owner' => true,
        'is_active' => true,
    ],
];